export {default as HomePage} from "./landing/Home";
export {default as AboutPage} from "./landing/About";
export {default as TreatmentPage} from "./landing/Treatment";
export {default as ContactPage} from "./landing/Contact";
export {default as AdminDashboard} from "./Protected/Admin/AdminDashboard";
export {default as UserDashboard} from "./Protected/User/UserDashboard";
export {default as LoginPage} from "./LoginPage";
export {default as LandingPage} from "./public/LandingPage";
export {default as ProtectedRoutes} from "./Protected/ProtectedRoutes";